import Nav from "@/Components/nav";
import "./globals.css";



export const metadata = {
  title: "Transportes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >

      <body>
        <header>
          <h2>Hola soy la cabecera de mi sitio.</h2>
        </header>
        <Nav/>

        {children}

        <footer>Hola soy el pie de mi sitio</footer>

      </body>
    </html>
  );
}
